### ISSUE TITLE
Can observer root and target span different frames that are same-origin?

### ISSUE THREAD

**Issue by szager-chromium** [slightlyoff/IntersectionObserver#66]

**Comment by ojanvafai** [comment]
Seems like this doesn't add any extra complexity aside from not walking all the way to the root, so may as well support it. Regardless of this decision, the algorithm in the spec needs to be updated to say what happens when you hit a frame boundary computing the bounding client rect. The right thing is to translate the root's document's coordinate system.

**Comment by szager-chromium** [comment]
Nothing to be done here.
