### ISSUE TITLE
MS Feedback: Avoiding layout goal seems problematic

### ISSUE THREAD

**Issue by travisleithead** [slightlyoff/IntersectionObserver#9]
#### Avoiding layout goal seems problematic

We can't think of a good design that eliminates the need to perform layout for these scenarios; using our (off thread) display tree state may be out of date and not necessarily backed by a related DOM element. Perhaps there's something we're missing?

The design goals seem conflicting: don't necessarily run layout, yet be able to report ```thresholdCallbacks:false``` and get quads with specific pixel-perfect dimensions. We feel like this should land firmly on the side of accurate reporting if we will go through the trouble of notifying at the specific times.

**Comment by ojanvafai** [comment]
The avoiding layout goal is for the ads use case. For ads, they don't care about the current state of the world. They only care about what happened in the past. That's why the change record includes the element's quads and the viewport's quads. They will be able to do all their work solely based off what's in the change record, which will avoid extra layouts due to things like calling getBoundingClientRect.

Similarly, I would guess that this would be good enough for the delay loading use case.

I expect for the list view use case, you'd still getBoundingClientRect in the callback to get up to date information, so you would force a layout, but that's actually less than or equal to the amount of forced layout you'd get today without PositionObserver.

Make sense?

**Comment by ojanvafai** [comment]
Closing issue. Please reopen if my previous comment does not address the concerns.
